![](distancia.png)

In [2]:
import pandas as pd
import numpy as np

df = pd.DataFrame(dict(x=[0, 2, 3, 5], y=[2, 0, 1, 1]))
df.index = [1, 2, 3, 4]
df

x  y
1  0  2
2  2  0
3  3  1
4  5  1

In [3]:
# Matriz de distancia n_puntos x n_puntos
n_puntos = 4
d_m = np.zeros((4, 4))
d_m  # coordenada i,j contiene la distancia entre pi, pj

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [6]:
p1 = df.iloc[0]  # p1
p2 = df.iloc[1]
p3 = df.iloc[2]
p4 = df.iloc[3]  # p4


def l2_distance(p, q):
    x1 = p["x"]
    x2 = q["x"]
    y1 = p["y"]
    y2 = q["y"]

    return np.sqrt((x1 - x2) ** 2 + (y1 - y2) ** 2)


l2_distance(p1, p4)

5.0990195135927845

In [12]:
def calculate_matrix(df, distance_func, n_puntos=4):
    d_m = np.zeros((n_puntos, n_puntos))
    for i in range(n_puntos):
        for j in range(n_puntos):
            p = df.iloc[i]
            q = df.iloc[j]
            d_m[i, j] = distance_func(p, q)

    return d_m


d_m = calculate_matrix(df, l2_distance)
d_m

array([[0.        , 2.82842712, 3.16227766, 5.09901951],
       [2.82842712, 0.        , 1.41421356, 3.16227766],
       [3.16227766, 1.41421356, 0.        , 2.        ],
       [5.09901951, 3.16227766, 2.        , 0.        ]])

In [14]:
def l1_distance(p, q):
    x1 = p["x"]
    x2 = q["x"]
    y1 = p["y"]
    y2 = q["y"]

    return np.abs(x1 - x2) + np.abs(y1 - y2)


def linf_distance(p, q):
    x1 = p["x"]
    x2 = q["x"]
    y1 = p["y"]
    y2 = q["y"]
    dist_x = np.abs(x1 - x2)
    dist_y = np.abs(y1 - y2)
    return np.max([dist_x, dist_y])


dm_l1 = calculate_matrix(df, l1_distance)
dm_linf = calculate_matrix(df, linf_distance)
dm_linf

array([[0., 2., 3., 5.],
       [2., 0., 1., 3.],
       [3., 1., 0., 2.],
       [5., 3., 2., 0.]])

![](distancia.png)