![](distancia.png)

In [1]:
import pandas as pd
import numpy as np

df = pd.DataFrame(dict(x=[0, 2, 3, 5], y=[2, 0, 1, 1]))
df.index = [1, 2, 3, 4]
df

x  y
1  0  2
2  2  0
3  3  1
4  5  1

In [2]:
np.zeros((4, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [3]:
def distancia_l1(p, q):
    x1 = p["x"]
    x2 = q["x"]
    y1 = p["y"]
    y2 = q["y"]

    return np.abs(x1 - x2) + np.abs(y1 - y2)


def distancia_l2(p, q):
    x1 = p["x"]
    x2 = q["x"]
    y1 = p["y"]
    y2 = q["y"]
    return np.sqrt((x1 - x2) ** 2 + (y1 - y2) ** 2)


def distancia_linf(p, q):
    x1 = p["x"]
    x2 = q["x"]
    y1 = p["y"]
    y2 = q["y"]
    d_x = np.abs(x1 - x2)
    d_y = np.abs(y1 - y2)
    return np.max([d_x, d_y])


def calculate_matrix(distance, n_puntos):
    m = np.zeros((n_puntos, n_puntos))
    for i in range(n_puntos):
        for j in range(n_puntos):
            p = df.iloc[i]
            q = df.iloc[j]
            m[i, j] = distance(p, q)

    return m


m_m = calculate_matrix(distancia_l1, 4)
m_e = calculate_matrix(distancia_l2, 4)
m_c = calculate_matrix(distancia_linf, 4)

In [4]:
m_m

array([[0., 4., 4., 6.],
       [4., 0., 2., 4.],
       [4., 2., 0., 2.],
       [6., 4., 2., 0.]])

In [5]:
m_e

array([[0.        , 2.82842712, 3.16227766, 5.09901951],
       [2.82842712, 0.        , 1.41421356, 3.16227766],
       [3.16227766, 1.41421356, 0.        , 2.        ],
       [5.09901951, 3.16227766, 2.        , 0.        ]])

In [6]:
m_c

array([[0., 2., 3., 5.],
       [2., 0., 1., 3.],
       [3., 1., 0., 2.],
       [5., 3., 2., 0.]])

![](distancia.png)

In [7]:
a = pd.Series(
    [1.0, 1.5, 2.0, 2.5, 3.0, 3.5, 4.0, 4.5, 5.0, 5.5, 6.0, 6.5, 7.0]
)
b = pd.Series(
    [1.0, 3.5, 3.6, 3.7, 3.8, 3.9, 4.0, 4.1, 4.2, 4.3, 4.4, 4.5, 7.0]
)

a.var(ddof=0)  # Varianza Poblacional

3.5

In [8]:
a.var(ddof=1)  # Varianza Muestral

3.7916666666666665

In [9]:
b.var(ddof=1)

1.5916666666666668